From Stdlib Require Import List Bool Arith Lia.
From CCont Require Import StringConstraints Syntax LookaheadSemantics
  LookaheadDerivatives LookaheadDecision PeriodicAutomaton.
Import ListNotations.
Set Implicit Arguments.

(** Derivation-oriented representatives for EVERY periodic state.
    Retain every nonempty product combination generated by Eq. (20), including
    products already covered semantically by singleton branches. The original
    period blocks are retained instead of expanding the common modulus. *)
Module PeriodicDisplay.

Definition shift_offset period shift :=
  let r := shift mod period in
  if Nat.eqb r 0 then 0 else period - r.

Lemma shift_offset_correct period shift n : period > 0 ->
  (n mod period = shift_offset period shift <-> (shift + n) mod period = 0).
Proof.
  intro Hp. unfold shift_offset.
  pose proof (Nat.mod_upper_bound shift period ltac:(lia)) as Hshift.
  pose proof (Nat.mod_upper_bound n period ltac:(lia)) as Hn.
  rewrite Nat.add_mod by lia.
  destruct (Nat.eqb (shift mod period) 0) eqn:E.
  - apply Nat.eqb_eq in E. rewrite E, Nat.add_0_l.
    now rewrite Nat.mod_mod by lia.
  - apply Nat.eqb_neq in E. split.
    + intro H. rewrite H.
      replace (shift mod period + (period - shift mod period)) with period by lia.
      apply Nat.mod_same. lia.
    + intro H. apply (proj1 (Nat.mod_divides
        (shift mod period + n mod period) period ltac:(lia))) in H as [k Hk].
      assert (Hk1 : k = 1) by nia. subst k. nia.
Qed.

Lemma shift_offset_bound period shift : period > 0 ->
  shift_offset period shift < period.
Proof.
  intro Hp. unfold shift_offset.
  pose proof (Nat.mod_upper_bound shift period ltac:(lia)).
  destruct (Nat.eqb (shift mod period) 0) eqn:E; [lia|].
  apply Nat.eqb_neq in E. lia.
Qed.

Fixpoint trigger_offsets {A} (eqb : A -> A -> bool) (trigger : A) (w : list A) :=
  match w with
  | [] => []
  | a :: w' =>
      let later := trigger_offsets eqb trigger w' in
      if eqb a trigger then later ++ [length w'] else later
  end.

Definition historyb periods offsets n :=
  existsb (fun shift => PeriodicFamily.periodsb periods (shift + n)) offsets.

Section Alphabet.
Context {A : Type}.
Variable eqb : A -> A -> bool.
Hypothesis eqb_spec : forall x y, eqb x y = true <-> x = y.
Variable sigma : regex A.
Hypothesis sigma_one : forall w, matches sigma w <-> length w = 1.
Variable trigger : A.

Definition shifted_assertion period shift :=
  WLookahead (embed_regex
    (PeriodicAutomaton.residue_regex sigma period (shift_offset period shift))).

Lemma shifted_assertion_semantics period shift u v : period > 0 ->
  (rewpla_denote eqb (shifted_assertion period shift) (u,v) <->
    u = [] /\ Nat.eqb ((shift + length v) mod period) 0 = true).
Proof.
  intro Hp. unfold shifted_assertion.
  assert (Hmatch : matches
    (PeriodicAutomaton.residue_regex sigma period (shift_offset period shift)) v
    <-> Nat.eqb ((shift + length v) mod period) 0 = true).
  { rewrite PeriodicAutomaton.residue_regex_correct; try assumption.
    - rewrite Nat.eqb_eq. apply shift_offset_correct. exact Hp.
    - apply shift_offset_bound. exact Hp. }
  split.
  - intros [p [Hp' Hout]].
    apply (proj1 (embed_regex_semantics eqb eqb_spec _ p)) in Hp'.
    destruct Hp' as [w [-> Hw]]. unfold constraint_projection in Hout.
    simpl in Hout. rewrite app_nil_r in Hout. inversion Hout; subst u v.
    split; [reflexivity|]. now apply Hmatch.
  - intros [-> Hv]. exists (v, []). split.
    + apply (proj2 (embed_regex_semantics eqb eqb_spec _ (v, []))).
      exists v. split; [reflexivity|now apply Hmatch].
    + unfold constraint_projection. simpl. now rewrite app_nil_r.
Qed.

Lemma union_expression_members xs p :
  rewpla_denote eqb (union_expression xs) p <->
  exists r, In r xs /\ rewpla_denote eqb r p.
Proof.
  induction xs as [|r xs IH]; simpl.
  - split; [contradiction|intros [r [H _]]; contradiction].
  - eapply iff_trans; [apply smart_plus_correct_M|].
    change (rewpla_denote eqb r p \/ rewpla_denote eqb (union_expression xs) p
      <-> exists s, In s (r::xs) /\ rewpla_denote eqb s p).
    rewrite IH. split.
    + intros [Hr|[s [Hs Hsp]]].
      * exists r. split; [now left|exact Hr].
      * exists s. split; [now right|exact Hsp].
    + intros [s [[<-|Hs] Hsp]]; [now left|]. right. exists s. now split.
Qed.

Fixpoint derivation_terms (cs : list (rewpla A)) : list (rewpla A) :=
  match cs with
  | [] => []
  | c :: rest =>
      let tail := derivation_terms rest in
      map (fun r => WConcat c r) tail ++ c :: tail
  end.

Lemma derivation_terms_length cs :
  length (derivation_terms cs) + 1 = 2 ^ length cs.
Proof.
  induction cs as [|c cs IH]; simpl; [reflexivity|].
  rewrite length_app, length_map. simpl. nia.
Qed.

(** These three inclusion lemmas mirror the three context-product branches
    Dc(R).Dc(S), Dc(R).lambda(S), lambda(R).Dc(S) of Eq. (20).
    All original periodic assertions have lambda = epsilon. Every nonempty
    combination is generated at the first step; its all-factor derivative
    remains present at subsequent steps, irrespective of epsilon guards. *)
Lemma derivation_terms_product_in c cs r :
  In r (derivation_terms cs) -> In (WConcat c r) (derivation_terms (c::cs)).
Proof. intro H. simpl. apply in_app_iff. left. now apply in_map. Qed.

Lemma derivation_terms_head_in c cs : In c (derivation_terms (c::cs)).
Proof. simpl. apply in_app_iff. right. now left. Qed.

Lemma derivation_terms_tail_in c cs r :
  In r (derivation_terms cs) -> In r (derivation_terms (c::cs)).
Proof. intro H. simpl. apply in_app_iff. right. now right. Qed.

Lemma derivation_terms_singletons cs c :
  In c cs -> In c (derivation_terms cs).
Proof.
  induction cs as [|x cs IH]; simpl; [contradiction|].
  intros [<-|H]; [apply derivation_terms_head_in|].
  apply derivation_terms_tail_in. now apply IH.
Qed.

Lemma derivation_terms_empty_main cs :
  (forall c, In c cs -> empty_main_language (rewpla_denote eqb c)) ->
  forall r, In r (derivation_terms cs) ->
    empty_main_language (rewpla_denote eqb r).
Proof.
  induction cs as [|c cs IH]; intros Hcs r Hr; simpl in Hr; [contradiction|].
  assert (Hc : empty_main_language (rewpla_denote eqb c)) by (apply Hcs; now left).
  assert (Htail : forall r, In r (derivation_terms cs) ->
      empty_main_language (rewpla_denote eqb r)).
  { apply IH. intros x Hx. apply Hcs. now right. }
  apply in_app_iff in Hr as [Hr|[<-|Hr]]; [|exact Hc|now apply Htail].
  apply in_map_iff in Hr as [s [<- Hs]].
  apply empty_main_concat; [exact eqb_spec|exact Hc|now apply Htail].
Qed.

Lemma zero_width_product_member c d p :
  empty_main_language (rewpla_denote eqb c) ->
  empty_main_language (rewpla_denote eqb d) ->
  rewpla_denote eqb (WConcat c d) p ->
  rewpla_denote eqb c p \/ rewpla_denote eqb d p.
Proof.
  intros Hc Hd [q1 [q2 [H1 [H2 Hout]]]].
  destruct q1 as [u1 v1], q2 as [u2 v2], p as [u v].
  specialize (Hc (u1,v1) H1). specialize (Hd (u2,v2) H2).
  simpl in Hc, Hd. subst u1 u2.
  pose proof (constraint_concat_result_shape eqb [] v1 [] v2 Hout) as [t Hp].
  inversion Hp; subst u t.
  apply (constraint_concat_empty_mains_result eqb eqb_spec v1 v2) in Hout.
  destruct Hout as [Heq|Heq]; subst v; [now left|now right].
Qed.

Lemma derivation_terms_members cs r p :
  (forall c, In c cs -> empty_main_language (rewpla_denote eqb c)) ->
  In r (derivation_terms cs) -> rewpla_denote eqb r p ->
  exists c, In c cs /\ rewpla_denote eqb c p.
Proof.
  revert r. induction cs as [|c cs IH]; intros r Hcs Hr Hp; simpl in Hr; [contradiction|].
  assert (Hc : empty_main_language (rewpla_denote eqb c)) by (apply Hcs; now left).
  assert (Htail : forall x, In x cs -> empty_main_language (rewpla_denote eqb x)).
  { intros x Hx. apply Hcs. now right. }
  apply in_app_iff in Hr as [Hr|[<-|Hr]].
  - apply in_map_iff in Hr as [s [<- Hs]].
    apply zero_width_product_member in Hp; [|exact Hc|].
    + destruct Hp as [Hp|Hp].
      * exists c. split; [now left|exact Hp].
      * destruct (IH s Htail Hs Hp) as [x [Hx Hxp]].
        exists x. split; [now right|exact Hxp].
    + eapply derivation_terms_empty_main; [exact Htail|exact Hs].
  - exists c. split; [now left|exact Hp].
  - destruct (IH r Htail Hr Hp) as [x [Hx Hxp]].
    exists x. split; [now right|exact Hxp].
Qed.

Theorem derivation_terms_semantics cs :
  (forall c, In c cs -> empty_main_language (rewpla_denote eqb c)) ->
  lang_equiv (rewpla_denote eqb (union_expression (derivation_terms cs)))
    (rewpla_denote eqb (union_expression cs)).
Proof.
  intros Hcs p. rewrite !union_expression_members. split.
  - intros [r [Hr Hp]]. eapply derivation_terms_members; eauto.
  - intros [c [Hc Hp]]. exists c. split; [now apply derivation_terms_singletons|exact Hp].
Qed.

Definition shift_expression periods shift :=
  if Nat.eqb shift 0 then PeriodicAutomaton.assertions sigma periods
  else union_expression
    (derivation_terms (map (fun p => shifted_assertion p shift) periods)).

Lemma shift_expression_semantics periods shift u v :
  periods <> [] -> Forall (fun p => p > 0) periods ->
  (rewpla_denote eqb (shift_expression periods shift) (u,v) <->
    u = [] /\ PeriodicFamily.periodsb periods (shift + length v) = true).
Proof.
  intros Hnon Hpos. unfold shift_expression.
  destruct (Nat.eqb shift 0) eqn:E.
  - apply Nat.eqb_eq in E. subst shift. simpl.
    rewrite PeriodicAutomaton.assertions_semantics; try assumption.
    rewrite PeriodicAutomaton.suffixb_nonempty by assumption. tauto.
  - assert (Hempty : forall c,
        In c (map (fun p => shifted_assertion p shift) periods) ->
        empty_main_language (rewpla_denote eqb c)).
    { intros c Hc. apply in_map_iff in Hc as [p [<- Hp]].
        intros [x y] Hxy. apply shifted_assertion_semantics in Hxy.
        - exact (proj1 Hxy).
        - rewrite Forall_forall in Hpos. now apply Hpos. }
    rewrite (derivation_terms_semantics
      (map (fun p => shifted_assertion p shift) periods) Hempty (u,v)).
    rewrite union_expression_members.
    unfold PeriodicFamily.periodsb. rewrite existsb_exists. split.
    + intros [r [Hin Hr]]. apply in_map_iff in Hin as [p [<- Hp]].
      apply shifted_assertion_semantics in Hr.
      * destruct Hr as [Hu Hv]. split; [exact Hu|]. exists p. now split.
      * rewrite Forall_forall in Hpos. now apply Hpos.
    + intros [Hu [p [Hp Hv]]]. exists (shifted_assertion p shift). split.
      * apply in_map_iff. exists p. now split.
      * apply shifted_assertion_semantics.
        -- rewrite Forall_forall in Hpos. now apply Hpos.
        -- now split.
Qed.

Definition history_expression periods offsets :=
  union_expression (nodupb (rewpla_eqb eqb)
    (map (shift_expression periods) offsets)).

Theorem history_expression_semantics periods offsets u v :
  periods <> [] -> Forall (fun p => p > 0) periods ->
  (rewpla_denote eqb (history_expression periods offsets) (u,v) <->
    u = [] /\ historyb periods offsets (length v) = true).
Proof.
  intros Hnon Hpos. unfold history_expression.
  rewrite union_expression_members. unfold historyb. rewrite existsb_exists. split.
  - intros [r [Hin Hr]].
    apply (proj1 (nodupb_in_iff (rewpla_eqb eqb)
      (rewpla_eqb_spec eqb eqb_spec) _ r)) in Hin.
    apply in_map_iff in Hin as [shift [<- Hshift]].
    apply shift_expression_semantics in Hr; try assumption.
    destruct Hr as [Hu Hv]. split; [exact Hu|]. exists shift. now split.
  - intros [Hu [shift [Hshift Hv]]]. exists (shift_expression periods shift). split.
    + apply (proj2 (nodupb_in_iff (rewpla_eqb eqb)
        (rewpla_eqb_spec eqb eqb_spec) _ _)). now apply in_map.
    + apply shift_expression_semantics; try assumption. now split.
Qed.

Lemma run_history_accepts modulus periods w s v :
  modulus <> 0 ->
  Forall (fun p => p <> 0 /\ Nat.divide p modulus) periods ->
  length s = modulus ->
  PeriodicFamily.accepts (PeriodicAutomaton.run eqb trigger modulus periods s w) v =
    (PeriodicFamily.accepts s (w ++ v) ||
      historyb periods (trigger_offsets eqb trigger w) (length v)).
Proof.
  intros Hmod Hperiods. revert s v.
  induction w as [|a w IH]; intros s v Hs; simpl.
  - now rewrite Bool.orb_false_r.
  - rewrite IH.
    2:{ rewrite PeriodicFamily.step_length; [exact Hs|].
        rewrite PeriodicFamily.base_length. symmetry. exact Hs. }
    unfold PeriodicFamily.step. destruct (eqb a trigger) eqn:E.
    + rewrite PeriodicFamily.accepts_union.
      2:{ rewrite PeriodicFamily.rotate_length, PeriodicFamily.base_length. exact Hs. }
      rewrite PeriodicFamily.accepts_base by assumption.
      unfold historyb. rewrite existsb_app. simpl. rewrite app_length.
      rewrite Bool.orb_false_r.
      rewrite <- (@PeriodicFamily.accepts_cons A s a (w ++ v)).
      destruct (PeriodicFamily.accepts s (a :: w ++ v)),
        (PeriodicFamily.periodsb periods (length w + length v)),
        (existsb (fun shift => PeriodicFamily.periodsb periods (shift + length v))
          (trigger_offsets eqb trigger w)); reflexivity.
    + rewrite <- (@PeriodicFamily.accepts_cons A s a (w ++ v)). reflexivity.
Qed.

Definition representative initial periods w :=
  smart_plus initial (history_expression periods (trigger_offsets eqb trigger w)).

Theorem representative_word_derivative_correct modulus periods w :
  modulus <> 0 -> periods <> [] ->
  Forall (fun p => p <> 0 /\ Nat.divide p modulus) periods ->
  lang_equiv (rewpla_denote eqb
    (word_derivative eqb w (PeriodicAutomaton.expression sigma trigger periods)))
    (rewpla_denote eqb
      (representative (PeriodicAutomaton.expression sigma trigger periods) periods w)).
Proof.
  intros Hmod Hnon Hperiods.
  assert (Hpos : Forall (fun p => p > 0) periods).
  { eapply Forall_impl; [|exact Hperiods]. intros p [Hp _]. lia. }
  eapply lang_equiv_trans.
  - apply (@PeriodicAutomaton.word_derivative_correspondence A eqb eqb_spec sigma
      sigma_one trigger modulus periods w Hmod Hnon Hperiods).
  - intros [u v]. unfold representative.
    rewrite (smart_plus_correct_M eqb _ _ (u,v)).
    change (PeriodicFamily.residual_language trigger
      (fun v => PeriodicFamily.periodsb periods (length v))
      (PeriodicAutomaton.run eqb trigger modulus periods (PeriodicFamily.zeros modulus) w)
      (u,v) <->
      rewpla_denote eqb (PeriodicAutomaton.expression sigma trigger periods) (u,v) \/
      rewpla_denote eqb
        (history_expression periods (trigger_offsets eqb trigger w)) (u,v)).
    rewrite PeriodicAutomaton.expression_semantics, history_expression_semantics
      by assumption.
    unfold PeriodicFamily.residual_language. simpl.
    rewrite run_history_accepts; try assumption; [|apply PeriodicFamily.zeros_length].
    rewrite PeriodicAutomaton.accepts_zeros. simpl.
    pose proof (PeriodicAutomaton.ends_in_nonempty (trigger := trigger) (u := u)).
    tauto.
Qed.

Theorem representative_word_derivative_correct_for_initial initial modulus periods w :
  modulus <> 0 -> periods <> [] ->
  Forall (fun p => p <> 0 /\ Nat.divide p modulus) periods ->
  lang_equiv (rewpla_denote eqb initial)
    (rewpla_denote eqb (PeriodicAutomaton.expression sigma trigger periods)) ->
  lang_equiv (rewpla_denote eqb (word_derivative eqb w initial))
    (rewpla_denote eqb (representative initial periods w)).
Proof.
  intros Hmod Hnon Hperiods Hinitial.
  eapply lang_equiv_trans.
  - eapply lang_equiv_trans.
    + apply word_derivative_correct. exact eqb_spec.
    + eapply lang_equiv_trans.
      * apply pair_language_word_quotient_compat. exact Hinitial.
      * apply lang_equiv_sym. apply word_derivative_correct. exact eqb_spec.
  - eapply lang_equiv_trans.
    + apply (representative_word_derivative_correct w
        (modulus := modulus)); assumption.
    + intros p. unfold representative.
      rewrite (smart_plus_correct_M eqb _ _ p), (smart_plus_correct_M eqb _ _ p).
      change (rewpla_denote eqb
        (PeriodicAutomaton.expression sigma trigger periods) p \/
        rewpla_denote eqb
          (history_expression periods (trigger_offsets eqb trigger w)) p <->
        rewpla_denote eqb initial p \/
        rewpla_denote eqb
          (history_expression periods (trigger_offsets eqb trigger w)) p).
      rewrite (Hinitial p). tauto.
Qed.
End Alphabet.
End PeriodicDisplay.

Module DerivationDisplay.

(** Output normalization removes zero branches and concatenation units, but
    does NOT erase LA(epsilon), nested assertions, or covered products.
    ACI merges only structurally identical union terms. State exploration may
    use stronger normalization; display is replayed from the original input. *)
Definition keep_lookahead {A} (r : rewpla A) :=
  match r with WZero => WZero | _ => WLookahead r end.

Lemma keep_lookahead_correct {A} eqb (r : rewpla A) :
  lang_equiv (rewpla_denote eqb (keep_lookahead r))
    (rewpla_denote eqb (WLookahead r)).
Proof.
  destruct r; simpl; try apply lang_equiv_refl.
  apply lang_equiv_sym. apply (rewpla_lookahead_zero_M eqb).
Qed.

Fixpoint normalize {A} (r : rewpla A) : rewpla A :=
  match r with
  | WZero => WZero
  | WEps => WEps
  | WAtom a => WAtom a
  | WPlus p q => smart_plus (normalize p) (normalize q)
  | WConcat p q => smart_concat (normalize p) (normalize q)
  | WStar p => smart_star (normalize p)
  | WLookahead p => keep_lookahead (normalize p)
  end.

Theorem normalize_correct {A} eqb
    (eqb_spec : forall x y : A, eqb x y = true <-> x = y) (r : rewpla A) :
  lang_equiv (rewpla_denote eqb (normalize r)) (rewpla_denote eqb r).
Proof.
  induction r; simpl; try apply lang_equiv_refl.
  - eapply lang_equiv_trans; [apply smart_plus_correct_M|].
    apply lang_union_compat; assumption.
  - eapply lang_equiv_trans; [apply smart_concat_correct_M; exact eqb_spec|].
    apply lang_concat_compat; assumption.
  - eapply lang_equiv_trans; [apply smart_star_correct_M; exact eqb_spec|].
    apply lang_star_compat; assumption.
  - eapply lang_equiv_trans; [apply keep_lookahead_correct|].
    apply positive_lookahead_compat; assumption.
Qed.

Definition canonical {A} eqb atom_code (r : rewpla A) :=
  rewpla_aci_normalize eqb atom_code (normalize r).

Lemma canonical_correct {A} eqb atom_code
    (eqb_spec : forall x y : A, eqb x y = true <-> x = y) (r : rewpla A) :
  lang_equiv (rewpla_denote eqb (canonical eqb atom_code r)) (rewpla_denote eqb r).
Proof.
  unfold canonical. eapply lang_equiv_trans.
  - apply rewpla_aci_normalize_correct; assumption.
  - apply normalize_correct; assumption.
Qed.

Definition symbol_step {A} eqb atom_code a (r : rewpla A) :=
  canonical eqb atom_code (derivative_merge (symbol_derivative_core eqb a r)).

Lemma symbol_step_correct {A} eqb atom_code
    (eqb_spec : forall x y : A, eqb x y = true <-> x = y) a (r : rewpla A) :
  lang_equiv (rewpla_denote eqb (symbol_step eqb atom_code a r))
    (pair_language_symbol_quotient eqb a (rewpla_denote eqb r)).
Proof.
  unfold symbol_step. eapply lang_equiv_trans.
  - apply canonical_correct; assumption.
  - apply symbol_derivative_core_merge_correct; assumption.
Qed.

Fixpoint word_step {A} eqb atom_code w (r : rewpla A) :=
  match w with
  | [] => canonical eqb atom_code r
  | a :: rest => word_step eqb atom_code rest (symbol_step eqb atom_code a r)
  end.

Theorem word_step_correct {A} eqb atom_code
    (eqb_spec : forall x y : A, eqb x y = true <-> x = y) w (r : rewpla A) :
  lang_equiv (rewpla_denote eqb (word_step eqb atom_code w r))
    (pair_language_word_quotient eqb w (rewpla_denote eqb r)).
Proof.
  revert r. induction w as [|a w IH]; intro r; simpl.
  - eapply lang_equiv_trans; [apply canonical_correct; assumption|].
    intro q. unfold pair_language_word_quotient. split.
    + intro Hq. exists q. now split.
    + intros [p [Hp Hstep]]. inversion Hstep; subst p. exact Hp.
  - eapply lang_equiv_trans; [apply IH|].
    eapply lang_equiv_trans.
    + apply pair_language_word_quotient_compat.
      apply symbol_step_correct; assumption.
    + apply lang_equiv_sym, pair_language_word_quotient_cons.
Qed.

Theorem word_step_derivative_correct {A} eqb atom_code
    (eqb_spec : forall x y : A, eqb x y = true <-> x = y) w (r : rewpla A) :
  lang_equiv (rewpla_denote eqb (word_step eqb atom_code w r))
    (rewpla_denote eqb (word_derivative eqb w r)).
Proof.
  eapply lang_equiv_trans; [apply word_step_correct; assumption|].
  apply lang_equiv_sym, word_derivative_correct; assumption.
Qed.

End DerivationDisplay.

Print Assumptions PeriodicDisplay.history_expression_semantics.
Print Assumptions PeriodicDisplay.derivation_terms_semantics.
Print Assumptions PeriodicDisplay.representative_word_derivative_correct.
Print Assumptions PeriodicDisplay.representative_word_derivative_correct_for_initial.
Print Assumptions DerivationDisplay.word_step_derivative_correct.
